[emfit]
    # Mapping of pins from the AUX cable to Raspberry Pi GPIO pins
    AUX_1_PIN = "BOARD9" # Common return (Ground, above pin 17. Not really needed to specify)
    AUX_2_PIN = 17       # Normally Open (NO) send
    AUX_3_PIN = 22       # Normally Closed (NC) send
    AUX_4_PIN = 27       # Low Battery send (NC)

[redcap]
    # Config data needed to send the alarms log to REDCap
    REDCAP_API_TOKEN  = "token here"      # Your REDCap project's API token
    REDCAP_API_URL    = "redcap url here" # The API URL of your REDCap instance
    REDCAP_FILE_FIELD = "file field here" # Set to the REDCap field for file upload
    REDCAP_RECORD_ID  = "record is here"  # Record ID of the patient. It needs to be a string of an integer.
